/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R503RouteImport } from './routes/503'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexLazyRouteImport = createFileRoute('/')()
const AuthenticatedTeamLazyRouteImport = createFileRoute(
  '/_authenticated/team',
)()
const AuthenticatedProjectsLazyRouteImport = createFileRoute(
  '/_authenticated/projects',
)()
const AuthenticatedLifecycleLazyRouteImport = createFileRoute(
  '/_authenticated/lifecycle',
)()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedAnalyticsLazyRouteImport = createFileRoute(
  '/_authenticated/analytics',
)()
const AuthenticatedShowcaseNavigationLazyRouteImport = createFileRoute(
  '/_authenticated/showcase/navigation',
)()
const AuthenticatedShowcaseFeedbackLazyRouteImport = createFileRoute(
  '/_authenticated/showcase/feedback',
)()
const AuthenticatedShowcaseCardsLazyRouteImport = createFileRoute(
  '/_authenticated/showcase/cards',
)()
const AuthenticatedShowcaseButtonsLazyRouteImport = createFileRoute(
  '/_authenticated/showcase/buttons',
)()
const AuthenticatedDocumentsWordAssistantLazyRouteImport = createFileRoute(
  '/_authenticated/documents/word-assistant',
)()
const AuthenticatedDocumentsReportsLazyRouteImport = createFileRoute(
  '/_authenticated/documents/reports',
)()
const AuthenticatedDocumentsDataLibraryLazyRouteImport = createFileRoute(
  '/_authenticated/documents/data-library',
)()

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R503Route = R503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AuthenticatedTeamLazyRoute = AuthenticatedTeamLazyRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/team.lazy').then((d) => d.Route),
)
const AuthenticatedProjectsLazyRoute =
  AuthenticatedProjectsLazyRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/projects.lazy').then((d) => d.Route),
  )
const AuthenticatedLifecycleLazyRoute =
  AuthenticatedLifecycleLazyRouteImport.update({
    id: '/lifecycle',
    path: '/lifecycle',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/lifecycle.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
  )
const AuthenticatedAnalyticsLazyRoute =
  AuthenticatedAnalyticsLazyRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/analytics.lazy').then((d) => d.Route),
  )
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShowcaseNavigationLazyRoute =
  AuthenticatedShowcaseNavigationLazyRouteImport.update({
    id: '/showcase/navigation',
    path: '/showcase/navigation',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/showcase.navigation.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedShowcaseFeedbackLazyRoute =
  AuthenticatedShowcaseFeedbackLazyRouteImport.update({
    id: '/showcase/feedback',
    path: '/showcase/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/showcase.feedback.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedShowcaseCardsLazyRoute =
  AuthenticatedShowcaseCardsLazyRouteImport.update({
    id: '/showcase/cards',
    path: '/showcase/cards',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/showcase.cards.lazy').then((d) => d.Route),
  )
const AuthenticatedShowcaseButtonsLazyRoute =
  AuthenticatedShowcaseButtonsLazyRouteImport.update({
    id: '/showcase/buttons',
    path: '/showcase/buttons',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/showcase.buttons.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDocumentsWordAssistantLazyRoute =
  AuthenticatedDocumentsWordAssistantLazyRouteImport.update({
    id: '/documents/word-assistant',
    path: '/documents/word-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/documents.word-assistant.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDocumentsReportsLazyRoute =
  AuthenticatedDocumentsReportsLazyRouteImport.update({
    id: '/documents/reports',
    path: '/documents/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/documents.reports.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDocumentsDataLibraryLazyRoute =
  AuthenticatedDocumentsDataLibraryLazyRouteImport.update({
    id: '/documents/data-library',
    path: '/documents/data-library',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/documents.data-library.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/analytics': typeof AuthenticatedAnalyticsLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/lifecycle': typeof AuthenticatedLifecycleLazyRoute
  '/projects': typeof AuthenticatedProjectsLazyRoute
  '/team': typeof AuthenticatedTeamLazyRoute
  '/documents/data-library': typeof AuthenticatedDocumentsDataLibraryLazyRoute
  '/documents/reports': typeof AuthenticatedDocumentsReportsLazyRoute
  '/documents/word-assistant': typeof AuthenticatedDocumentsWordAssistantLazyRoute
  '/showcase/buttons': typeof AuthenticatedShowcaseButtonsLazyRoute
  '/showcase/cards': typeof AuthenticatedShowcaseCardsLazyRoute
  '/showcase/feedback': typeof AuthenticatedShowcaseFeedbackLazyRoute
  '/showcase/navigation': typeof AuthenticatedShowcaseNavigationLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/analytics': typeof AuthenticatedAnalyticsLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/lifecycle': typeof AuthenticatedLifecycleLazyRoute
  '/projects': typeof AuthenticatedProjectsLazyRoute
  '/team': typeof AuthenticatedTeamLazyRoute
  '/documents/data-library': typeof AuthenticatedDocumentsDataLibraryLazyRoute
  '/documents/reports': typeof AuthenticatedDocumentsReportsLazyRoute
  '/documents/word-assistant': typeof AuthenticatedDocumentsWordAssistantLazyRoute
  '/showcase/buttons': typeof AuthenticatedShowcaseButtonsLazyRoute
  '/showcase/cards': typeof AuthenticatedShowcaseCardsLazyRoute
  '/showcase/feedback': typeof AuthenticatedShowcaseFeedbackLazyRoute
  '/showcase/navigation': typeof AuthenticatedShowcaseNavigationLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsLazyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/lifecycle': typeof AuthenticatedLifecycleLazyRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsLazyRoute
  '/_authenticated/team': typeof AuthenticatedTeamLazyRoute
  '/_authenticated/documents/data-library': typeof AuthenticatedDocumentsDataLibraryLazyRoute
  '/_authenticated/documents/reports': typeof AuthenticatedDocumentsReportsLazyRoute
  '/_authenticated/documents/word-assistant': typeof AuthenticatedDocumentsWordAssistantLazyRoute
  '/_authenticated/showcase/buttons': typeof AuthenticatedShowcaseButtonsLazyRoute
  '/_authenticated/showcase/cards': typeof AuthenticatedShowcaseCardsLazyRoute
  '/_authenticated/showcase/feedback': typeof AuthenticatedShowcaseFeedbackLazyRoute
  '/_authenticated/showcase/navigation': typeof AuthenticatedShowcaseNavigationLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/auth/callback'
    | '/analytics'
    | '/dashboard'
    | '/lifecycle'
    | '/projects'
    | '/team'
    | '/documents/data-library'
    | '/documents/reports'
    | '/documents/word-assistant'
    | '/showcase/buttons'
    | '/showcase/cards'
    | '/showcase/feedback'
    | '/showcase/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/auth/callback'
    | '/analytics'
    | '/dashboard'
    | '/lifecycle'
    | '/projects'
    | '/team'
    | '/documents/data-library'
    | '/documents/reports'
    | '/documents/word-assistant'
    | '/showcase/buttons'
    | '/showcase/cards'
    | '/showcase/feedback'
    | '/showcase/navigation'
  id:
    | '__root__'
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/auth/callback'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/lifecycle'
    | '/_authenticated/projects'
    | '/_authenticated/team'
    | '/_authenticated/documents/data-library'
    | '/_authenticated/documents/reports'
    | '/_authenticated/documents/word-assistant'
    | '/_authenticated/showcase/buttons'
    | '/_authenticated/showcase/cards'
    | '/_authenticated/showcase/feedback'
    | '/_authenticated/showcase/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  R503Route: typeof R503Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/503': {
      id: '/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof R503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lifecycle': {
      id: '/_authenticated/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof AuthenticatedLifecycleLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/showcase/navigation': {
      id: '/_authenticated/showcase/navigation'
      path: '/showcase/navigation'
      fullPath: '/showcase/navigation'
      preLoaderRoute: typeof AuthenticatedShowcaseNavigationLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/feedback': {
      id: '/_authenticated/showcase/feedback'
      path: '/showcase/feedback'
      fullPath: '/showcase/feedback'
      preLoaderRoute: typeof AuthenticatedShowcaseFeedbackLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/cards': {
      id: '/_authenticated/showcase/cards'
      path: '/showcase/cards'
      fullPath: '/showcase/cards'
      preLoaderRoute: typeof AuthenticatedShowcaseCardsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/buttons': {
      id: '/_authenticated/showcase/buttons'
      path: '/showcase/buttons'
      fullPath: '/showcase/buttons'
      preLoaderRoute: typeof AuthenticatedShowcaseButtonsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/word-assistant': {
      id: '/_authenticated/documents/word-assistant'
      path: '/documents/word-assistant'
      fullPath: '/documents/word-assistant'
      preLoaderRoute: typeof AuthenticatedDocumentsWordAssistantLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/reports': {
      id: '/_authenticated/documents/reports'
      path: '/documents/reports'
      fullPath: '/documents/reports'
      preLoaderRoute: typeof AuthenticatedDocumentsReportsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/data-library': {
      id: '/_authenticated/documents/data-library'
      path: '/documents/data-library'
      fullPath: '/documents/data-library'
      preLoaderRoute: typeof AuthenticatedDocumentsDataLibraryLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsLazyRoute: typeof AuthenticatedAnalyticsLazyRoute
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedLifecycleLazyRoute: typeof AuthenticatedLifecycleLazyRoute
  AuthenticatedProjectsLazyRoute: typeof AuthenticatedProjectsLazyRoute
  AuthenticatedTeamLazyRoute: typeof AuthenticatedTeamLazyRoute
  AuthenticatedDocumentsDataLibraryLazyRoute: typeof AuthenticatedDocumentsDataLibraryLazyRoute
  AuthenticatedDocumentsReportsLazyRoute: typeof AuthenticatedDocumentsReportsLazyRoute
  AuthenticatedDocumentsWordAssistantLazyRoute: typeof AuthenticatedDocumentsWordAssistantLazyRoute
  AuthenticatedShowcaseButtonsLazyRoute: typeof AuthenticatedShowcaseButtonsLazyRoute
  AuthenticatedShowcaseCardsLazyRoute: typeof AuthenticatedShowcaseCardsLazyRoute
  AuthenticatedShowcaseFeedbackLazyRoute: typeof AuthenticatedShowcaseFeedbackLazyRoute
  AuthenticatedShowcaseNavigationLazyRoute: typeof AuthenticatedShowcaseNavigationLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsLazyRoute: AuthenticatedAnalyticsLazyRoute,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedLifecycleLazyRoute: AuthenticatedLifecycleLazyRoute,
  AuthenticatedProjectsLazyRoute: AuthenticatedProjectsLazyRoute,
  AuthenticatedTeamLazyRoute: AuthenticatedTeamLazyRoute,
  AuthenticatedDocumentsDataLibraryLazyRoute:
    AuthenticatedDocumentsDataLibraryLazyRoute,
  AuthenticatedDocumentsReportsLazyRoute:
    AuthenticatedDocumentsReportsLazyRoute,
  AuthenticatedDocumentsWordAssistantLazyRoute:
    AuthenticatedDocumentsWordAssistantLazyRoute,
  AuthenticatedShowcaseButtonsLazyRoute: AuthenticatedShowcaseButtonsLazyRoute,
  AuthenticatedShowcaseCardsLazyRoute: AuthenticatedShowcaseCardsLazyRoute,
  AuthenticatedShowcaseFeedbackLazyRoute:
    AuthenticatedShowcaseFeedbackLazyRoute,
  AuthenticatedShowcaseNavigationLazyRoute:
    AuthenticatedShowcaseNavigationLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  R503Route: R503Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
