// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CreateIssueDto = {
  actual_behavior?: string | null;
  assignee?: string | null;
  description?: string | null;
  expected_behavior?: string | null;
  metadata?: string | null;
  priority?: string | null;
  reproduce_steps?: string | null;
  source_id?: string | null;
  source_name?: string | null;
  source_url?: string | null;
  tags?: Array<string> | null;
  title: string;
};

export type Issue = {
  actual_behavior?: string | null;
  ai_analysis?: string | null;
  assignee?: string | null;
  created_at: string;
  description?: string | null;
  expected_behavior?: string | null;
  id: string;
  is_verified: boolean;
  metadata?: string | null;
  priority: string;
  reproduce_steps?: string | null;
  resolution_reason?: string | null;
  source_id?: string | null;
  source_name?: string | null;
  source_url?: string | null;
  status: string;
  tags: string;
  title: string;
  updated_at: string;
  verified_at?: string | null;
};

export type ListIssuesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/issues';
};

export type ListIssuesResponses = {
  /**
   * List all issues
   */
  200: Array<Issue>;
};

export type ListIssuesResponse = ListIssuesResponses[keyof ListIssuesResponses];

export type CreateIssueData = {
  body: CreateIssueDto;
  path?: never;
  query?: never;
  url: '/api/issues';
};

export type CreateIssueResponses = {
  /**
   * Issue created successfully
   */
  201: Issue;
};

export type CreateIssueResponse = CreateIssueResponses[keyof CreateIssueResponses];

export type BatchCreateIssuesData = {
  body: Array<CreateIssueDto>;
  path?: never;
  query?: never;
  url: '/api/issues/batch';
};

export type BatchCreateIssuesResponses = {
  /**
   * Batch accepted for processing
   */
  202: unknown;
};

export type DeleteIssueData = {
  body?: never;
  path: {
    /**
     * Issue ID
     */
    id: string;
  };
  query?: never;
  url: '/api/issues/{id}';
};

export type DeleteIssueErrors = {
  /**
   * Issue not found
   */
  404: unknown;
};

export type DeleteIssueResponses = {
  /**
   * Issue deleted successfully
   */
  204: void;
};

export type DeleteIssueResponse = DeleteIssueResponses[keyof DeleteIssueResponses];

export type GetIssueData = {
  body?: never;
  path: {
    /**
     * Issue ID
     */
    id: string;
  };
  query?: never;
  url: '/api/issues/{id}';
};

export type GetIssueErrors = {
  /**
   * Issue not found
   */
  404: unknown;
};

export type GetIssueResponses = {
  /**
   * Get issue by ID
   */
  200: Issue;
};

export type GetIssueResponse = GetIssueResponses[keyof GetIssueResponses];

export type UpdateIssueData = {
  body: CreateIssueDto;
  path: {
    /**
     * Issue ID
     */
    id: string;
  };
  query?: never;
  url: '/api/issues/{id}';
};

export type UpdateIssueErrors = {
  /**
   * Issue not found
   */
  404: unknown;
};

export type UpdateIssueResponses = {
  /**
   * Issue updated successfully
   */
  200: Issue;
};

export type UpdateIssueResponse = UpdateIssueResponses[keyof UpdateIssueResponses];
