/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as R503RouteImport } from './routes/503'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as AutomaAuthRouteImport } from './routes/automa.auth'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorkspaceBrowserProfilesRouteImport } from './routes/_workspace/browser-profiles'
import { Route as WorkspaceAppStoreRouteImport } from './routes/_workspace/app-store'
import { Route as WorkspaceAppStoreAppIdRouteImport } from './routes/_workspace/app-store_.$appId'

const IndexLazyRouteImport = createFileRoute('/')()
const WorkspaceAppAppIdLazyRouteImport = createFileRoute(
  '/_workspace/app/$appId',
)()

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const R503Route = R503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AutomaAuthRoute = AutomaAuthRouteImport.update({
  id: '/automa/auth',
  path: '/automa/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceBrowserProfilesRoute =
  WorkspaceBrowserProfilesRouteImport.update({
    id: '/browser-profiles',
    path: '/browser-profiles',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceAppStoreRoute = WorkspaceAppStoreRouteImport.update({
  id: '/app-store',
  path: '/app-store',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAppAppIdLazyRoute = WorkspaceAppAppIdLazyRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => WorkspaceRoute,
} as any).lazy(() =>
  import('./routes/_workspace/app.$appId.lazy').then((d) => d.Route),
)
const WorkspaceAppStoreAppIdRoute = WorkspaceAppStoreAppIdRouteImport.update({
  id: '/app-store_/$appId',
  path: '/app-store/$appId',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/app-store': typeof WorkspaceAppStoreRoute
  '/browser-profiles': typeof WorkspaceBrowserProfilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automa/auth': typeof AutomaAuthRoute
  '/app-store/$appId': typeof WorkspaceAppStoreAppIdRoute
  '/app/$appId': typeof WorkspaceAppAppIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/app-store': typeof WorkspaceAppStoreRoute
  '/browser-profiles': typeof WorkspaceBrowserProfilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automa/auth': typeof AutomaAuthRoute
  '/app-store/$appId': typeof WorkspaceAppStoreAppIdRoute
  '/app/$appId': typeof WorkspaceAppAppIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/503': typeof R503Route
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/_workspace/app-store': typeof WorkspaceAppStoreRoute
  '/_workspace/browser-profiles': typeof WorkspaceBrowserProfilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automa/auth': typeof AutomaAuthRoute
  '/_workspace/app-store_/$appId': typeof WorkspaceAppStoreAppIdRoute
  '/_workspace/app/$appId': typeof WorkspaceAppAppIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/app-store'
    | '/browser-profiles'
    | '/auth/callback'
    | '/automa/auth'
    | '/app-store/$appId'
    | '/app/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/app-store'
    | '/browser-profiles'
    | '/auth/callback'
    | '/automa/auth'
    | '/app-store/$appId'
    | '/app/$appId'
  id:
    | '__root__'
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/_workspace'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/_workspace/app-store'
    | '/_workspace/browser-profiles'
    | '/auth/callback'
    | '/automa/auth'
    | '/_workspace/app-store_/$appId'
    | '/_workspace/app/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  R503Route: typeof R503Route
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AutomaAuthRoute: typeof AutomaAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/503': {
      id: '/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof R503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automa/auth': {
      id: '/automa/auth'
      path: '/automa/auth'
      fullPath: '/automa/auth'
      preLoaderRoute: typeof AutomaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/browser-profiles': {
      id: '/_workspace/browser-profiles'
      path: '/browser-profiles'
      fullPath: '/browser-profiles'
      preLoaderRoute: typeof WorkspaceBrowserProfilesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/app-store': {
      id: '/_workspace/app-store'
      path: '/app-store'
      fullPath: '/app-store'
      preLoaderRoute: typeof WorkspaceAppStoreRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/app/$appId': {
      id: '/_workspace/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof WorkspaceAppAppIdLazyRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/app-store_/$appId': {
      id: '/_workspace/app-store_/$appId'
      path: '/app-store/$appId'
      fullPath: '/app-store/$appId'
      preLoaderRoute: typeof WorkspaceAppStoreAppIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAppStoreRoute: typeof WorkspaceAppStoreRoute
  WorkspaceBrowserProfilesRoute: typeof WorkspaceBrowserProfilesRoute
  WorkspaceAppStoreAppIdRoute: typeof WorkspaceAppStoreAppIdRoute
  WorkspaceAppAppIdLazyRoute: typeof WorkspaceAppAppIdLazyRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAppStoreRoute: WorkspaceAppStoreRoute,
  WorkspaceBrowserProfilesRoute: WorkspaceBrowserProfilesRoute,
  WorkspaceAppStoreAppIdRoute: WorkspaceAppStoreAppIdRoute,
  WorkspaceAppAppIdLazyRoute: WorkspaceAppAppIdLazyRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  R503Route: R503Route,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AutomaAuthRoute: AutomaAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
