// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  BatchCreateIssuesData,
  BatchCreateIssuesResponses,
  CreateIssueData,
  CreateIssueResponses,
  DeleteIssueData,
  DeleteIssueErrors,
  DeleteIssueResponses,
  GetIssueData,
  GetIssueErrors,
  GetIssueResponses,
  ListIssuesData,
  ListIssuesResponses,
  UpdateIssueData,
  UpdateIssueErrors,
  UpdateIssueResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listIssues = <ThrowOnError extends boolean = false>(
  options?: Options<ListIssuesData, ThrowOnError>,
): RequestResult<ListIssuesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListIssuesResponses, unknown, ThrowOnError>({
    url: '/api/issues',
    ...options,
  });

export const createIssue = <ThrowOnError extends boolean = false>(
  options: Options<CreateIssueData, ThrowOnError>,
): RequestResult<CreateIssueResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CreateIssueResponses, unknown, ThrowOnError>({
    url: '/api/issues',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const batchCreateIssues = <ThrowOnError extends boolean = false>(
  options: Options<BatchCreateIssuesData, ThrowOnError>,
): RequestResult<BatchCreateIssuesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<BatchCreateIssuesResponses, unknown, ThrowOnError>({
    url: '/api/issues/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteIssue = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIssueData, ThrowOnError>,
): RequestResult<DeleteIssueResponses, DeleteIssueErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteIssueResponses, DeleteIssueErrors, ThrowOnError>({
    url: '/api/issues/{id}',
    ...options,
  });

export const getIssue = <ThrowOnError extends boolean = false>(
  options: Options<GetIssueData, ThrowOnError>,
): RequestResult<GetIssueResponses, GetIssueErrors, ThrowOnError> =>
  (options.client ?? client).get<GetIssueResponses, GetIssueErrors, ThrowOnError>({
    url: '/api/issues/{id}',
    ...options,
  });

export const updateIssue = <ThrowOnError extends boolean = false>(
  options: Options<UpdateIssueData, ThrowOnError>,
): RequestResult<UpdateIssueResponses, UpdateIssueErrors, ThrowOnError> =>
  (options.client ?? client).put<UpdateIssueResponses, UpdateIssueErrors, ThrowOnError>({
    url: '/api/issues/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
